### ISSUE TITLE
Separate Meshes for Each Brush

### ISSUE THREAD

**Issue by humansandbag** [codecat/godot-tbloader#84] opened 2023-07-15 18:49 UTC
This plugin creates a single Array Mesh for the entire map. In old BSP game engines, you could hit individual brushes with a raycast for doing various things like getting the texture name for that specific brush. Please change it so that Build Meshes creates separate meshes and collision shapes for each brush.

**Comment by krazyjakee** [comment] 2023-07-23 20:50
Dupe of #71

**Closed** 2023-07-24 01:54 UTC
